# ----------------------- #
#      Main Configs       #
# ----------------------- #

#url: http://yoursite.com
baseurl: http://joeyisnotcodemonkey.github.io/GoSheng/
#baseurl:
title: 安徽高盛化工
email: zhangzewei008@gmail.com
author: ZEWEI ZHANG
description: '安徽高盛化工股份有限公司坐落于安徽省重点化工园区，企业一直以来专注于精细化工产品的研发、生产和销售，本着“精进自己，分享他人”的企业理念，我们将精湛工艺和丰富经验相融合，针对客户的需求，开发出高纯度的对苯二胺、邻苯二胺、间苯二胺等产品。'
copyright: 'Copyright &copy; 2015 Anhui GoShen Chemical Co., Ltd. All Rights Reserved.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: wechat
